In [1]:
import numpy as np

In [2]:
x= np.array([2,4,6,8,10])
y= np.array([5,5,5,5,5])

In [3]:
x*y

array([10, 20, 30, 40, 50])

In [5]:
z=10

In [7]:
x*z #transmite la misma dimencion de x con multiplicar el escalar z

array([ 20,  40,  60,  80, 100])

In [8]:
ones = np.ones((3,4))

In [9]:
ones*z

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [10]:
t_s=[184,243,192,309,257,218]
we=[1178,1243,1403,1047,1673,1475]

In [12]:
c_info = np.array([t_s, we])
c_info

array([[ 184,  243,  192,  309,  257,  218],
       [1178, 1243, 1403, 1047, 1673, 1475]])

In [14]:
cv_factors=np.array([0.621371, 2.20462])#1Km=0.62 millas; 1Kg 2.2 lb

In [16]:
print(cv_factors.shape)
print(c_info.shape)

(2,)
(2, 6)


In [20]:
#c_info*cv_factors
n_factors=cv_factors.reshape(2,1)
c_info*n_factors

array([[ 114.332264,  150.993153,  119.303232,  192.003639,  159.692347,
         135.458878],
       [2597.04236 , 2740.34266 , 3093.08186 , 2308.23714 , 3688.32926 ,
        3251.8145  ]])