In [2]:
import numpy as np
import csv

In [3]:
x=np.arange(14)**2
x

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169])

In [4]:
#accesar por 'inices
x[3],x[7],x[9],x[13]

(9, 49, 81, 169)

In [5]:
#accesar por arreglo
mask_1=[3,7,9,13]

In [6]:
x[mask_1]

array([  9,  49,  81, 169])

In [7]:
mask_2=np.array([[3,5],[2,8]])
mask_2

array([[3, 5],
       [2, 8]])

In [8]:
#imprime de la misma forma que el arreglo de la mascara 
x[mask_2]

array([[ 9, 25],
       [ 4, 64]])

In [9]:
ciudades=np.array([["Sy","Auckl","Vanc"],["Lima","Bogota","Lisbon"],["Istanbul","Theran","Colombo"]])

In [10]:
# elementos fila 0 , col 0 , elemnto f 0 col 2, elemento f2 c0 y repite el elemento
row = np.array([[0,0],[2,2]])
col = np.array([[0,2],[0,0]])

In [11]:
#formato de arreglo anteriores
ciudades[row,col]

array([['Sy', 'Vanc'],
       ['Istanbul', 'Istanbul']], dtype='<U8')

In [12]:
ciudades[1,2]

'Lisbon'

In [13]:
#otra indexacion para modificar
ciudades[row,col] = 'city'
ciudades

array([['city', 'Auckl', 'city'],
       ['Lima', 'Bogota', 'Lisbon'],
       ['city', 'Theran', 'Colombo']], dtype='<U8')

In [14]:
mask_1

[3, 7, 9, 13]

In [15]:
x[mask_1]= 666
x

array([  0,   1,   4, 666,  16,  25,  36, 666,  64, 666, 100, 121, 144,
       666])