In [1]:
import numpy as np


In [4]:
x=np.arange(8)
print(x)

[0 1 2 3 4 5 6 7]


In [9]:
y=np.arange(16).reshape(4,4)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [11]:
#tridimencional
z=np.arange(36).reshape(3,4,3)
print(z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [13]:
#vector gigante
np.arange(12100)

array([    0,     1,     2, ..., 12097, 12098, 12099])

In [16]:
#2dmatriz
print(np.arange(12100).reshape(110,110))

[[    0     1     2 ...   107   108   109]
 [  110   111   112 ...   217   218   219]
 [  220   221   222 ...   327   328   329]
 ...
 [11770 11771 11772 ... 11877 11878 11879]
 [11880 11881 11882 ... 11987 11988 11989]
 [11990 11991 11992 ... 12097 12098 12099]]


In [17]:
#np.set_printoptions(threshold=np.nan)


ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation

In [19]:
np.set_printoptions(threshold=50)
print(np.arange(100).reshape(10,10))

[[ 0  1  2 ...  7  8  9]
 [10 11 12 ... 17 18 19]
 [20 21 22 ... 27 28 29]
 ...
 [70 71 72 ... 77 78 79]
 [80 81 82 ... 87 88 89]
 [90 91 92 ... 97 98 99]]
