In [1]:
import numpy as np

In [2]:
x = np.arange(10)**3
x

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [3]:
for i in x:
    print(x)

[  0   1   8  27  64 125 216 343 512 729]
[  0   1   8  27  64 125 216 343 512 729]
[  0   1   8  27  64 125 216 343 512 729]
[  0   1   8  27  64 125 216 343 512 729]
[  0   1   8  27  64 125 216 343 512 729]
[  0   1   8  27  64 125 216 343 512 729]
[  0   1   8  27  64 125 216 343 512 729]
[  0   1   8  27  64 125 216 343 512 729]
[  0   1   8  27  64 125 216 343 512 729]
[  0   1   8  27  64 125 216 343 512 729]


In [4]:
#bidimencional
#companias arreglo bi
companias=np.array([['Sam','MS','IBM','Spotify','FLipk'],[1938,1975,1911,2006,2007],[489000,131000,380000,3000,30000]])


In [5]:
#iteracion tipo clasica
#contador 0
i=0
for row in companias:
    print('Row', i,':',row)
    i+=1

Row 0 : ['Sam' 'MS' 'IBM' 'Spotify' 'FLipk']
Row 1 : ['1938' '1975' '1911' '2006' '2007']
Row 2 : ['489000' '131000' '380000' '3000' '30000']


In [6]:
# de 2 dimeciones a vector
companias.flatten()

array(['Sam', 'MS', 'IBM', 'Spotify', 'FLipk', '1938', '1975', '1911',
       '2006', '2007', '489000', '131000', '380000', '3000', '30000'],
      dtype='<U11')

In [7]:
#imprime el contenido del arreglo en tipo vector de Fortran
for data in companias.flatten(order='F'):
    print(data)

Sam
1938
489000
MS
1975
131000
IBM
1911
380000
Spotify
2006
3000
FLipk
2007
30000


In [8]:
num = np.arange(16).reshape(4,4)
num

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
#iterar nditer elementos individuales
for i in np.nditer(num):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [10]:
#iterar nditer elementos individuales estilo Fortran
for i in np.nditer(num, order='F'):
    print(i)

0
4
8
12
1
5
9
13
2
6
10
14
3
7
11
15


In [11]:
#iterar nditer elementos individuales estilo Fortran y 
for i in np.nditer(num, order='F', flags=['external_loop']):
    print(i)

[ 0  4  8 12]
[ 1  5  9 13]
[ 2  6 10 14]
[ 3  7 11 15]


In [13]:
#elemento por si mismo 
for array in np.nditer(num, op_flags=['readwrite']):
    array[...]=array*array

In [14]:
num

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])