In [1]:
import numpy as np

In [2]:
arreglo_1=np.array([0,1,3,5,7,9])

In [5]:
num=[11,22,33,44,55,66,77]
arreglo_2=np.array(num)


In [8]:
#arreglo de 0, 2 filas 3 columnas
arreglo_0=np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
#arreglo de 1, 3 filas 2 columnas, dtype cambia el tipo de dato de float a int
arreglo_unos=np.ones((3,2),dtype=np.int32)


In [17]:
#sin valores ni 0 ni 1 3 filas 2 columnas solo estructura
arreglo_vacios=np.empty((3,2))
arreglo_vacios

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
#cuadrada de 4 filas y columnas con diagonal de 1 y elementos 0
arreglo_ojo=np.eye(4)
arreglo_ojo

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
#arreglo lineal desde 2 a 24 en paso de 2 
arreglo_pares=np.arange(2,24,2)
arreglo_pares

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [24]:
arreglo_flotante=np.arange(1,3,0.3)
arreglo_flotante

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8])

In [27]:
#tipo bidimencional,los primeros valores son filas
arreglo_2D=np.array([(3,4,6),(2,1,6)])
arreglo_2D.shape

(2, 3)

In [28]:
#vector o arreglo de 8 elementos de 1 en 1
np.arange(8)


array([0, 1, 2, 3, 4, 5, 6, 7])

In [32]:
#remodelacion de 2 filas 4 columnas, numero de elementos debe ser adecuado
arreglo_nd=np.arange(8).reshape(2,4)
arreglo_nd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [34]:
#arreflo de unos similar a la matriz arreglo_nd en dimenciones
arreglo_unos_nd=np.ones_like(arreglo_nd)
arreglo_unos_nd

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])