In [2]:
import numpy as np

In [3]:
p=np.array([9,8,7])
q=np.array([3,2,4])

In [5]:
#suma elemento a elemento
p+q

array([12, 10, 11])

In [6]:
#diferencia elemento a elemento
p-q

array([6, 6, 3])

In [7]:
#modulo%2 del vector p
p%2

array([1, 0, 1], dtype=int32)

In [8]:
#booleanos elementos mayores a 8
p>8

array([ True, False, False])

In [9]:
#bidimencionales
X=np.array([[2,1],[1,3]])
Y=np.array([[3,2],[4,2]])
print('X: \n', X)
print('Y: \n', Y)

X: 
 [[2 1]
 [1 3]]
Y: 
 [[3 2]
 [4 2]]


In [10]:
#suma elemento a elemento
X+Y

array([[5, 3],
       [5, 5]])

In [11]:
#multiplicacion elemento a elemento
X*Y

array([[6, 2],
       [4, 6]])

In [12]:
#producto punto 2 matrices
X.dot(Y)

array([[10,  6],
       [15,  8]])

In [13]:
np.dot(X,Y)

array([[10,  6],
       [15,  8]])

In [14]:
#producto cruz
np.cross(X,Y)

array([  1, -10])

In [15]:
X*=4
X

array([[ 8,  4],
       [ 4, 12]])

In [18]:
coches_recorrido=np.array([14130,37234,21892,11479,6890,27981])

In [19]:
#suma de los objetos del arreglo
coches_recorrido.sum()

119606

In [22]:
#minimo del arreglo
coches_recorrido.min()
#max del arreglo
coches_recorrido.max()
#promedio
coches_recorrido.mean()

19934.333333333332

In [28]:
#bidimencionales
numeros=np.arange(16).reshape(4,4)
numeros.sum()

120

In [29]:
numeros

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
#suma las columnas
numeros.sum(axis=0)

array([24, 28, 32, 36])

In [27]:
#suma las filas
numeros.sum(axis=1)

array([ 6, 22, 38, 54])

In [30]:
#minimo en filas valor de las filas
numeros.min(axis=1)

array([ 0,  4,  8, 12])