In [1]:
import numpy as np

In [2]:
x=np.arange(10)**3
x

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [3]:
#elemento del indice 3
x[3]

27

In [5]:
#contando desde el ultimo
x[-4]

216

In [6]:
#desde 1 a 8
x[1:8]

array([  1,   8,  27,  64, 125, 216, 343], dtype=int32)

In [7]:
#desde 
x[3:-3]

array([ 27,  64, 125, 216], dtype=int32)

In [8]:
#desde 0 a 8 en indice
x[:8]

array([  0,   1,   8,  27,  64, 125, 216, 343], dtype=int32)

In [9]:
#desde 3 al ultimo en indice
x[3:]

array([ 27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [10]:
#orden inverso
x[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

In [11]:
#companias arreglo bi
companias=np.array([['Sam','MS','IBM','Spotify','FLipk'],[1938,1975,1911,2006,2007],[489000,131000,380000,3000,30000]])


In [15]:
companias[0] #fila


array(['Sam', 'MS', 'IBM', 'Spotify', 'FLipk'], dtype='<U11')

In [17]:
companias[:,2] #columna

array(['IBM', '1911', '380000'], dtype='<U11')

In [18]:
#celda en particular
companias[0,2]


'IBM'

In [19]:
#fila o columna completa
companias[0:2, 2:4]

array([['IBM', 'Spotify'],
       ['1911', '2006']], dtype='<U11')

In [20]:
companias[:, 2:4]
#todas las filas pero columnas 2 y 4

array([['IBM', 'Spotify'],
       ['1911', '2006'],
       ['380000', '3000']], dtype='<U11')

In [21]:
#ultima fila
companias[-1, :]

array(['489000', '131000', '380000', '3000', '30000'], dtype='<U11')

In [24]:
companias[0, ...]# resto matriz fila 0 al final de las columnas

array(['Sam', 'MS', 'IBM', 'Spotify', 'FLipk'], dtype='<U11')

In [25]:
companias[..., 2]# resto matriz columna2 y todas las filas

array(['IBM', '1911', '380000'], dtype='<U11')