In [1]:
import numpy as np

In [2]:
radio_circulo=np.array([145,120,90,60,45,30])

In [4]:
diametros_circulo=2*radio_circulo
diametros_circulo

array([290, 240, 180, 120,  90,  60])

In [6]:
areas_circulo=np.pi*radio_circulo**2
areas_circulo

array([66051.98554173, 45238.93421169, 25446.90049408, 11309.73355292,
        6361.72512352,  2827.43338823])

In [7]:
angulos_grados=np.array([0,30,60,90,120,150,180])


In [9]:
angulos_rad=angulos_grados*np.pi/180
angulos_rad

array([0.        , 0.52359878, 1.04719755, 1.57079633, 2.0943951 ,
       2.61799388, 3.14159265])

In [10]:
print('seno angulos: ')
np.sin(angulos_rad)

seno angulos: 


array([0.00000000e+00, 5.00000000e-01, 8.66025404e-01, 1.00000000e+00,
       8.66025404e-01, 5.00000000e-01, 1.22464680e-16])

In [11]:
print('arcoseno angulos: ')
np.arcsin(np.sin(angulos_rad))

arcoseno angulos: 


array([0.00000000e+00, 5.23598776e-01, 1.04719755e+00, 1.57079633e+00,
       1.04719755e+00, 5.23598776e-01, 1.22464680e-16])

In [12]:
print('arcoseno angulos en grados: ')
np.arcsin(np.sin(angulos_rad))*180/np.pi

arcoseno angulos en grados: 


array([0.0000000e+00, 3.0000000e+01, 6.0000000e+01, 9.0000000e+01,
       6.0000000e+01, 3.0000000e+01, 7.0167093e-15])

In [14]:
#e^x
x=np.arange(4,31,5)
expo=np.exp(x)
expo

array([5.45981500e+01, 8.10308393e+03, 1.20260428e+06, 1.78482301e+08,
       2.64891221e+10, 3.93133430e+12])

In [16]:
#raizcuadrada de x
sqrt=np.sqrt(x)
sqrt

array([2.        , 3.        , 3.74165739, 4.35889894, 4.89897949,
       5.38516481])

In [2]:
#arreglo flotantes
flotar_values=np.genfromtxt('datasets/float_values.csv', delimiter=',')

In [9]:
#stadisticas e NP
print('media= %i' %np.mean(flotar_values))
print('mediana= %i' %np.median(flotar_values))
print('varianza= %i' %np.var(flotar_values))
print('SD= %i' %np.std(flotar_values))

media= 16
mediana= 5
varianza= 1659
SD= 40
